apps/mobile/tsconfig.app.json, apps/mobile/tsconfig.spec.json
tsconfig improved to reduce error in imports file
=> INHEART-136: Fix tsconfig

README.md, apps/mobile-e2e/src/app.spec.ts, apps/mobile/src/app/pages/Homepage/Homepage.tsx
- first e2e test added
- readme updated
=> Inheart 118

libs/ui/atoms/src/lib/Box/__tests__/Box.spec.tsx, libs/ui/atoms/src/lib/Button/__tests__/Button.spec.tsx, libs/ui/atoms/src/lib/Center/__tests__/Center.spec.tsx, libs/ui/atoms/src/lib/Container/__tests__/Container.spec.tsx, libs/ui/atoms/src/lib/Icons/__tests__/Icons.spec.tsx, libs/ui/atoms/src/lib/Image/__tests__/Image.spec.tsx, libs/ui/atoms/src/lib/Input/__tests__/Input.spec.tsx, libs/ui/atoms/src/lib/Stack/__tests__/Stack.spec.tsx, libs/ui/molecules/src/lib/LoginFormControl/__tests__/LoginFormControl.spec.tsx
Add NativeBaseProvider to existing unit tests
=> INHEART-171: Fix unit tests

.storybook/story-loader.js, libs/ui/molecules/src/lib/LoginFormControl/__stories__/LoginFormControl.stories.tsx
Bugfix for storybook, url in configuration file added
=> INHEART-158: FIX storybook

package.json, yarn.lock
* INHEART-201: Hotfix
* INHEART-201: Hotfix 2
* INHEART-201: Hotfix 3
Co-authored-by: Konrad Hanus <konrad.hanus@intive.com>
=> Hotfix (#29)

apps/backend/src/app/app.module.ts, apps/backend/src/app/auctions/auctions.controller.ts, apps/backend/src/app/auctions/auctions.module.ts, apps/backend/src/app/auctions/auctions.service.ts, apps/backend/src/app/auctions/dto/create-auction.dto.ts, apps/backend/src/app/auctions/entities/auction.entity.ts, apps/backend/src/app/categories/categories.controller.spec.ts, apps/backend/src/app/categories/categories.controller.ts, apps/backend/src/app/categories/categories.module.ts, apps/backend/src/app/categories/categories.service.spec.ts, apps/backend/src/app/categories/categories.service.ts, apps/backend/src/app/categories/dto/create-category.dto.ts, apps/backend/src/app/categories/dto/update-category.dto.ts, apps/backend/src/app/categories/entities/category.entity.ts, apps/backend/src/app/categories/validators/category-exists.ts, apps/backend/src/app/common/dto/pagination-query.dto.ts, apps/backend/src/app/common/interceptors/not-found.interceptor.spec.ts, apps/backend/src/app/common/interceptors/not-found.interceptor.ts, apps/backend/src/main.ts, package.json, yarn.lock
Added:
- Categories entity, CRUD,
- Auction - Category relation,
- Auctions pagination,
- Error interceptor to catch EntityNotFoundError and return HTTP 404 NotFoundException,
- Validation.
Removed HTTP exceptions from auctions service layer.
Create category 
Get category 
Get non-existing category (interceptor used)
(error in console)
Create auction with category
Then, getting this auction:
Get all auctions: 
With limit: 
With offset:
With limit and offset: 
Validation - create auction without category
(console)
=> Inheart 282 - Add categories, update auctions

apps/backend/src/app/app.module.ts, apps/backend/src/app/auctions/auctions.controller.ts, apps/backend/src/app/auctions/auctions.module.ts, apps/backend/src/app/auctions/auctions.service.ts, apps/backend/src/app/auctions/dto/create-auction.dto.ts, apps/backend/src/app/auctions/entities/auction.entity.ts, apps/backend/src/app/categories/categories.controller.spec.ts, apps/backend/src/app/categories/categories.controller.ts, apps/backend/src/app/categories/categories.module.ts, apps/backend/src/app/categories/categories.service.spec.ts, apps/backend/src/app/categories/categories.service.ts, apps/backend/src/app/categories/dto/create-category.dto.ts, apps/backend/src/app/categories/dto/update-category.dto.ts, apps/backend/src/app/categories/entities/category.entity.ts, apps/backend/src/app/categories/validators/category-exists.ts, apps/backend/src/app/common/dto/pagination-query.dto.ts, apps/backend/src/app/common/interceptors/not-found.interceptor.spec.ts, apps/backend/src/app/common/interceptors/not-found.interceptor.ts, apps/backend/src/main.ts, package.json, yarn.lock
* INHEART-282: Add validation packages
* INHEART-282: Add validation pipe
* INHEART-282: Add validation rules to auction
* INHEART-282: Add categories
* INHEART-282: Add pagination dto
* INHEART-282: Add categories to auctions, add pagination
* INHEART-282: Add not found err interceptor
* INHEART-282: Add ordering by ID
* INHEART-282: Add throwing validation http exceptions
* INHEART-282: Add date fields to entities
* INHEART-282: Remove manual dealing with errors
* INHEART-282: Add get auctions limit if not set
* INHEART-282: Add max limit to pagination query
* INHEART-282: Remove transform propery from ValidationPipe
* INHEART-282: Restore transform property in ValidationPipe
* INHEART-282: Add maximum lengths and description field
* INHEART-282: Add minimum lengths
* INHEART-282: Clean …
=> Inheart 282 - Add categories, update auctions 

apps/mobile/ios/Podfile.lock, apps/mobile/src/app/components/Auctions/AuctionsPage.tsx, apps/mobile/src/app/components/Auctions/AuctionsTemplate.tsx, apps/mobile/src/main.tsx, libs/ui/molecules/src/lib/AuctionAuthor/AuctionAuthor.tsx, libs/ui/molecules/src/lib/AuctionHearts/AuctionHearts.tsx, libs/ui/organisms/src/lib/AuctionCard/AuctionCard.tsx, libs/ui/organisms/src/lib/AuctionsList/AuctionsList.tsx, yarn.lock
Fixed those issues:
- star colour is different from the design,
- no "already added to favourite" state, also not considered in the design,
- text to icons proportions are slightly different on author and price.
For now, user favorites functionality is just frontend mock, will be BE in the future, of course.
Reverted registerComponent to Mobile so that it could work on iOS simulator.
Removed x padding from auctions page.
Fixed top safe area.
EDIT: star color and position to decide 😄
=> Inheart 148 updates

apps/mobile/package.json, libs/ui/molecules/src/lib/CategoryFilter/CategoryFilter.tsx
- delete space on underline filter 
- hide filtering area after clicking
=> INHEART-155: Hot Fix issue - PR comments 

.vscode/settings.json, apps/mobile/src/app/components/Register/RegisterPage.tsx, apps/mobile/src/app/components/Register/RegisterTemplate.tsx, apps/mobile/src/app/components/Register/register-form-values.ts, package.json, yarn.lock
Make sure that only intive email is allowed
TS version updated along with eslint TS plugin
=> INHEART-336: Validate intive email and update TS version

libs/ui/organisms/src/lib/AppHeader/AppHeader.tsx
Add menu for logout
Just UI, click on logout menu item does nothing
=> INHEART-336: Add menu for logout

apps/backend/src/app/app.module.ts, apps/mobile/src/app/components/Register/RegisterPage.tsx, apps/mobile/src/app/components/Register/RegisterTemplate.tsx, libs/ui/molecules/src/lib/LoginFormControl/LoginFormControl.tsx, libs/ui/organisms/src/index.ts, libs/ui/organisms/src/lib/Inputs/EmailInput.tsx, libs/ui/organisms/src/lib/Inputs/index.ts
Make email input generic and add validation message
=> INHEART-373: Make email input generic

apps/backend/src/app/app.module.ts, apps/backend/src/auth/auth.service.ts, apps/mobile/src/app/App.tsx, apps/mobile/src/app/components/AuctionCreate/AuctionCreatePage.tsx, apps/mobile/src/app/components/AuctionCreate/AuctionCreateTemplate.tsx, apps/mobile/src/app/components/AuctionCreate/auction-create-form-values.ts, apps/mobile/src/app/components/Providers/UserProvider.tsx, libs/ui/molecules/src/lib/LoginFormControl/LoginFormControl.tsx, libs/ui/organisms/src/lib/AppHeader/AppHeader.tsx, libs/ui/organisms/src/lib/FooterMenu/FooterMenu.tsx
Improve authorization
Fix numeric input
=> Inheart 338: Improve authorization

apps/backend/src/app/auctions/auctions.service.ts
Return only auctions which are active
=> Inheart 337

apps/mobile/src/app/components/Auction/AuctionTemplate.tsx, libs/ui/molecules/src/index.ts, libs/ui/molecules/src/lib/AuctionBid/AuctionBid.tsx, libs/ui/molecules/src/lib/AuctionBid/index.tsx, libs/ui/molecules/src/lib/AuctionTime/AuctionTime.tsx
=> Inheart 384: Add auction bid UI

apps/mobile/src/app/components/Auction/AuctionTemplate.tsx, apps/mobile/src/app/components/Auction/BidModal.tsx, apps/mobile/src/app/components/Auction/bid-styles.ts, apps/mobile/src/app/components/AuctionCreate/AuctionCreateTemplate.tsx
Add confirmation modal for auction bid
Add max date for auction expiration - 1 month. It means that user is not allowed to make auction longer than 1 month
=> Inheart 337 part2

apps/backend/src/app/auctions/auctions.controller.ts, apps/backend/src/app/auctions/auctions.service.ts, apps/mobile/src/app/components/AuctionCreate/AuctionCreateTemplate.tsx, apps/mobile/src/app/components/Auctions/AuctionsPage.tsx, apps/mobile/src/app/components/Auctions/AuctionsTemplate.tsx, apps/mobile/src/app/components/Auctions/useFetchAutions.tsx, libs/data/src/routing/routes.ts, libs/ui/molecules/src/lib/CategoryFilter/CategoryFilter.tsx, libs/ui/molecules/src/lib/CategoryFilter/__stories__/CategoryFilter.stories.tsx, libs/ui/molecules/src/lib/CategoryFilter/__tests__/CategoryFilter.spec.tsx, libs/ui/organisms/src/lib/FilteringArea/FilteringArea.tsx
- Using categories in filter from BE, 
- changes on backend and frontend side
- fixed sorting and filtering
- code refactoring
- adding create category page
=> Inheart 324

libs/ui/organisms/src/lib/Inputs/EmailInput.tsx
=> INHEART-375: Fix email regex

apps/mobile/src/app/components/Auction/BidModal.tsx, libs/ui/molecules/src/index.ts, libs/ui/molecules/src/lib/CustomModal/CustomModal.tsx, libs/ui/molecules/src/lib/CustomModal/index.tsx, libs/ui/molecules/src/lib/CustomModal/styles.ts
=> INHEART-341: Make modal generic

apps/mobile/src/app/components/Auction/AuctionTemplate.tsx, apps/mobile/src/app/components/AuthenticatedPageWrapper/AuthenticatedPageWrapper.tsx, libs/ui/atoms/src/index.ts, libs/ui/atoms/src/lib/Loader/Loader.tsx, libs/ui/atoms/src/lib/Loader/index.ts
Loader is taken from here https://reactnative.dev/docs/activityindicator
=> INHEART-341: Add generic loader

apps/mobile/src/app/components/AuctionCreate/AuctionCreateTemplate.tsx, libs/ui/organisms/src/lib/AppFooter/AppFooter.tsx, libs/ui/organisms/src/lib/AuctionCard/AuctionCard.tsx, libs/ui/organisms/src/lib/AuctionHeader/AuctionHeader.tsx
The link was getting black background color when user kept it clicked. When I add underlayColor='transparent' property to each link this problem dissapeared. The pictures below shows the icons when the user clicked on them. I corrected it and I removed this black background color.
=> INHEART-357: Visual link issue

apps/mobile/src/app/components/Register/RegisterPage.tsx
I added logic which is responsible for converting email address to lower cases during register process.
=> INHEART-411 Convert email for lower cases during register process

apps/mobile/src/app/components/Register/RegisterPage.tsx
User is navigated to login screen after provide correct data in register form. 
TODO: handle errors when user provide incorrect data https://tracker.intive.com/jira/secure/RapidBoard.jspa?rapidView=1212&projectKey=INHEART&view=planning&selectedIssue=INHEART-418&issueLimit=100
=> INHEART-417 add navigation to login screen after successful register process

apps/mobile/src/app/components/Auction/AuctionTemplate.tsx, apps/mobile/src/app/components/AuctionCreate/AuctionCreateTemplate.tsx, libs/ui/shared/utils.ts
Fix price input (avoid showing NaN)
=> INHEART-412: Fix Price input

libs/ui/molecules/src/lib/LoginFormControl/LoginFormControl.tsx
The same like on register screen I added logic which is responsible for converting email for lower case during login process.
=> INHEART-410: Convert email address to lower case during login process

apps/backend/src/app/auctions/auctions.controller.ts, apps/backend/src/app/auctions/auctions.service.ts, apps/mobile/src/app/components/MyAuctions/MyAuctions.tsx, apps/mobile/src/app/components/MyAuctions/index.tsx, apps/mobile/src/app/routing/routes-config.tsx, apps/mobile/src/app/routing/routing-path.ts, libs/data/src/routing/routes.ts, libs/ui/organisms/src/lib/AppHeader/AppHeader.tsx
=> INHEART-397: Add my auctions page

apps/backend/src/app/auctions/entities/auction.entity.ts, apps/backend/src/app/categories/entities/category.entity.ts, apps/backend/src/app/users/entities/user.entity.ts, apps/mobile/src/app/components/AuctionCreate/AuctionCreatePage.tsx, apps/mobile/src/app/components/AuctionCreate/AuctionCreateTemplate.tsx, apps/mobile/src/app/components/Categories/CategoriesPage.tsx, apps/mobile/src/app/components/MyAuctions/MyAuctions.tsx, apps/mobile/src/app/components/Register/RegisterPage.tsx, libs/data/src/auctions/auction.ts, libs/data/src/auctions/auctions.mock.ts, libs/data/src/categories/categories.mock.ts, libs/data/src/categories/category.ts, libs/ui/molecules/src/lib/LoginFormControl/LoginFormControl.tsx
Fix MyAuctions
Fix type in BE model
Fix form validation
=> INHEART-397: Show auctions in my auctions

apps/mobile/src/app/components/MyAuctions/AuctionRow.tsx, apps/mobile/src/app/components/MyAuctions/MyAuctions.tsx, apps/mobile/src/app/components/MyAuctions/styles.ts, libs/ui/atoms/src/lib/Icon/Icon.tsx
=> INHEART-397: New design

apps/mobile/src/app/components/AuctionCreate/AuctionCreateTemplate.tsx, libs/ui/atoms/src/index.ts, libs/ui/atoms/src/lib/Input/NumberInput.tsx, libs/ui/atoms/src/lib/Input/index.ts, libs/ui/atoms/tsconfig.lib.json
I corrected the minimum and maximum price value and I created number input as a separate component.
=> INHEART-338: Price input (number)

apps/mobile/ios/Podfile.lock, apps/mobile/package.json, apps/mobile/src/app/assets/styles.tsx, apps/mobile/src/app/components/SignIn/SignInTemplate.tsx, apps/mobile/tsconfig.spec.json, package.json, yarn.lock
I displayed app version on login screen.
=> INHEART-419: Display app version

apps/mobile/src/app/components/AuthenticatedPageWrapper/AuthenticatedPageWrapper.tsx, apps/mobile/src/app/components/Register/RegisterTemplate.tsx
I added support for android system back button. 
1. When user is on sign in screen and HomeScreen: system back button minimizes application,
2. When user is on register screen: system back button directed to sign in screen,
3. When user is on one of main pages (from footer menu) system back button directed to home page,
4. When user is on other page than those listed above back button directed to previous screen.
=> INHEART-414: Support for system back button behaviour

apps/mobile/src/app/components/AuctionCreate/AuctionCreateTemplate.tsx
Fix max date for Expires at input
=> Inheart 337 fix max date

apps/mobile/src/app/components/MyAuctions/MyAuctions.tsx, apps/mobile/src/app/routing/routes-config.tsx, apps/mobile/src/app/routing/routing-path.ts, libs/data/src/routing/routes.ts, libs/ui/organisms/src/lib/AppHeader/AppHeader.tsx
=> Inheart 398 Add my bids page

apps/backend/src/app/users/entities/user.entity.ts, apps/backend/src/app/users/users.service.ts, apps/backend/src/auth/auth.controller.ts, apps/backend/src/auth/auth.service.ts, apps/backend/src/auth/types/user.ts, apps/mobile/src/app/components/Register/RegisterTemplate.tsx, libs/ui/molecules/src/lib/LoginFormControl/LoginFormControl.tsx, libs/ui/organisms/src/lib/Inputs/PasswordInput.tsx, libs/ui/organisms/src/lib/Inputs/index.ts
=> Inheart 430 Add password input

apps/backend/src/app/assets/entities/asset.entity.ts, apps/backend/src/app/auctions/entities/auction.entity.ts, apps/backend/src/app/categories/entities/category.entity.ts, apps/backend/src/app/users/entities/user.entity.ts
=> INHEART-438

apps/backend/src/app/auctions/auctions.controller.ts, apps/backend/src/app/auctions/auctions.service.ts, apps/backend/src/app/auctions/auctions.types.ts, apps/backend/src/app/auctions/auctions.utils.ts, apps/backend/src/app/bids/entities/bid.entity.ts, apps/mobile/src/app/components/MyAuctions/MyAuctions.tsx, apps/mobile/src/app/routing/routes-config.tsx, libs/data/src/routing/routes.ts, libs/ui/organisms/src/lib/AppHeader/AppHeader.tsx
=> INHEART-398: Add endpoint

apps/backend/src/app/auctions/auctions.controller.ts, apps/backend/src/app/auctions/auctions.service.ts, apps/backend/src/app/auctions/auctions.types.ts, apps/backend/src/app/auctions/auctions.utils.ts
Add search endpoint (extendable)
Currently supported:
- search by bid author
=> INHEART-392: Add search endpoint

.github/workflows/master_inheartive-api.yml, apps/mobile/android/app/build.gradle, apps/mobile/ios/inHEARTive.app.dSYM/Contents/Info.plist, apps/mobile/ios/inHEARTive/Info.plist, apps/mobile/package.json, changelog.md, package.json
- INHEART-439: Update version (#152)
=> Merge DEVELOP to MASTER v2.0.2

apps/mobile/android/app/src/main/java/com/intive/inheartive/MainApplication.java, apps/mobile/ios/inHEARTive/AppDelegate.mm
https://tracker.intive.com/jira/browse/INHEART-446
=> INHEART-446: Added force override for only lightmode

apps/backend/src/app/auctions/auctions.module.ts, apps/backend/src/app/auctions/validators/auction-exists.ts, apps/backend/src/app/bids/bids.service.ts, apps/backend/src/app/bids/dto/create-bid.dto.ts
INHEART-447: Update auction price during bidding
Add transaction to bidding action for security reason. This feature provides an additional update to the auction table apart of bids table update. Transaction was mainly implemented to avoid updating only one of them.
=> INHEART-447: Update auction price during bidding

apps/mobile/ios/inHEARTive/AppDelegate.mm, apps/mobile/src/app/components/Register/RegisterTemplate.tsx
https://tracker.intive.com/jira/browse/INHEART-440
=> INHEART-440: Top padding should be bigger so the Email field is visible and clickable

apps/mobile/src/app/components/Auction/AuctionTemplate.tsx, apps/mobile/src/app/components/AuctionCreate/AuctionCreateTemplate.tsx, apps/mobile/src/app/components/AuctionCreate/auction-create-form-values.ts, libs/data/src/auctions/auction.ts, libs/ui/atoms/src/lib/Icon/Icon.tsx, libs/ui/molecules/src/index.ts, libs/ui/molecules/src/lib/AuctionLocation/AuctionLocation.tsx, libs/ui/molecules/src/lib/AuctionLocation/TextStyled/index.tsx, libs/ui/molecules/src/lib/AuctionLocation/__tests__/AuctionLocation.spec.tsx, libs/ui/molecules/src/lib/AuctionLocation/index.tsx
https://tracker.intive.com/jira/browse/INHEART-451
Also added location info on AuctionDetails
=> INHEART-451: FE Add location in "Add Auction form" 

apps/backend/src/app/users/entities/user.entity.ts, apps/backend/src/app/users/users.controller.ts
INHEART-465: Serialization of password and salt fields of user entity in API responses
[INHEART-465](https://tracker.intive.com/jira/browse/INHEART-465)
=> INHEART-465: Serialization of password and salt fields of user entity in API responses

frontend/package.json, frontend/src/components/AuctionCreate/AuctionCreateTemplate.tsx
replace DatePicker lib with a new one due the current is incompatible with the Expo Go app
=> replace DatePicker lib with new one

frontend/src/components/AuthenticatedPageWrapper/AuthenticatedPageWrapper.tsx, frontend/src/libs/ui/organisms/src/AppHeader/AppHeader.tsx
https://tracker.intive.com/jira/browse/INHEART-456
=> INHEART-456: Too much top padding in iPhone XR

frontend/src/components/AuctionCreate/AuctionCreatePage.tsx, frontend/src/libs/ui/theme/src/colors.ts
https://tracker.intive.com/jira/browse/INHEART-497
=> INHEART-497 show toast when auction created successfully or error

frontend/src/components/SignIn/SignInTemplate.tsx
https://tracker.intive.com/jira/browse/INHEART-504
=> INHEART-504 make content width max 1024 px

backend/src/app/auctions/dto/create-auction.dto.ts
https://tracker.intive.com/jira/browse/INHEART-508
=> INHEART-508: Creating new auction is not possible with high price

frontend/src/components/SignIn/SignInTemplate.tsx
https://tracker.intive.com/jira/browse/INHEART-502
=> INHEART-502 change image size to show logo properly on web

backend/src/main.ts, frontend/src/libs/ui/atoms/src/Select/SelectItem.tsx, frontend/src/libs/ui/organisms/src/AppHeader/AppHeader.tsx
https://tracker.intive.com/jira/browse/INHEART-507
=> INHEART-507: Problem with signing in and registering in web version

frontend/src/components/Auction/AuctionTemplate.tsx, frontend/src/components/AuctionCreate/AuctionCreatePage.tsx, frontend/src/components/Categories/CategoriesPage.tsx, frontend/src/components/Register/RegisterPage.tsx, frontend/src/libs/ui/molecules/src/LoginFormControl/LoginFormControl.tsx, frontend/src/libs/ui/shared/utils.ts
https://tracker.intive.com/jira/browse/INHEART-350
https://tracker.intive.com/jira/browse/INHEART-351
=> INHEART-350/1: Create utilities for requests

backend/src/app/auctions/auctions.controller.ts, backend/src/app/auctions/dto/auction.dto.ts, backend/src/app/auctions/dto/create-auction.dto.ts, backend/src/app/auctions/dto/delete-auction.dto.ts, backend/src/app/auctions/dto/update-auction.dto.ts, backend/src/app/bids/dto/bid.dto.ts, backend/src/app/categories/dto/category.dto.ts, backend/src/app/users/dto/user.dto.ts, backend/yarn.lock
https://tracker.intive.com/jira/browse/INHEART-510
=> INHEART-510 create swagger docs for auctions

backend/src/app/auctions/auctions.service.ts, backend/src/app/categories/categories.controller.ts, backend/src/app/categories/categories.service.ts, backend/src/app/categories/dto/create-category.dto.ts, backend/src/app/categories/dto/update-category.dto.ts
https://tracker.intive.com/jira/browse/INHEART-511
=> INHEART-511 swagger docs for categories api

backend/src/app/auctions/auctions.service.ts, backend/src/app/bids/bids.service.ts, backend/src/app/users/dto/create-user.dto.ts, backend/src/app/users/users.controller.ts, backend/src/app/users/users.service.ts
https://tracker.intive.com/jira/browse/INHEART-513
=> INHEART-513 swagger doc for users api

backend/src/app/assets/assets.controller.ts, backend/src/app/assets/assets.service.ts, backend/src/app/assets/dto/asset.dto.ts, backend/src/app/assets/dto/create-asset.dto.ts
https://tracker.intive.com/jira/browse/INHEART-515
=> INHEART-515 add swagger doc for assets api

backend/src/app/auctions/auctions.controller.ts, backend/src/app/auctions/auctions.service.ts, backend/src/app/bids/bids.controller.ts, backend/src/app/bids/bids.service.ts, backend/src/app/bids/dto/bid.dto.ts, backend/src/app/bids/dto/create-bid.dto.ts
https://tracker.intive.com/jira/browse/INHEART-556
=> INHEART-556 refactor cyclic dependency between Bid and Auction

backend/src/app/bids/bids.controller.ts, backend/src/app/bids/dto/create-bid.dto.ts
https://tracker.intive.com/jira/browse/INHEART-512
=> INHEART-512 swagger doc for bids

frontend/src/libs/ui/organisms/src/AppHeader/AppHeader.tsx
user component in header goes out of page in smaller screen. To fix that problem i added max width to Select in header. Currently it's smaller but still have good width to fit all items (screen below). The rest changes were added automatically by prettier.
https://tracker.intive.com/jira/browse/INHEART-568
Solution:
=> INHEART-568: header goes out of page
